### ISSUE TITLE
Versa and Versa 2 support?

### ISSUE THREAD

**Issue by LarsNorgaard** [IanSavchenko/fitbit-week-number#3]
I know you don't make any money off this app, but would really love to have this app on my Versa 2 watch :)

**Comment by IanSavchenko** [comment]
Hi Lars! I will look into it!

**Comment by IanSavchenko** [comment]
Hi again, @LarsNorgaard! I checked it and there shouldn't be any problem getting it on Versa. Is it an issue for you? What happens when you open https://gallery.fitbit.com/details/d33414a8-f309-4438-aeee-d7dbc749420f on your phone with Fitbit app installed?

**Comment by LarsNorgaard** [comment]
It says not available on my device. Think it's because I have the Versa 2.

**Comment by LarsNorgaard** [comment]
And thank you so far Ian :)

**Comment by IanSavchenko** [comment]
Happy to help! 
Seems like the problem is that the app is using buttons (even though you can still swipe between weeks) and Versa 2 does not have buttons. Thus the app has to be approved by the moderators. I will try to make a UI change to show the swipe moves in a better way. Here is the info https://community.fitbit.com/t5/SDK-Development/App-not-compatible-for-Versa-2/td-p/3804170

**Comment by IanSavchenko** [comment]
So version 2.0 should be in the Store any moment now for all the models!
